entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    watch: true
    exposedByDefault: false
  # file:
  #   watch: true
  #   filename: /etc/traefik/ssl.yml

log:
  level: INFO
  # filePath: /var/log/traefik/traefik.log
accessLog: {}
